[package]
name = "saswatch"
version = "0.2.3"
edition = "2021"

[dependencies]
better-panic = "0.3.0"
clipboard = "0.5.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
directories = "5.0.1"
lazy_static = "1.5.0"
palette = "0.7.6"
rand = "0.8.5"
ratatui = { version = "0.29.0", features = ["palette"] }
